package monstersweeper

const (
	EDGE_MARGIN = 20
	SCREENWIDTH = 1280
	SCREENHEIGHT = 720
	TILE_MARGIN = 5
	GAME_AREA_WIDTH = SCREENWIDTH - 2 * EDGE_MARGIN
	GAME_AREA_HEIGHT = SCREENHEIGHT - 2 * EDGE_MARGIN
	TILE_SIZE_X = (GAME_AREA_WIDTH - 6 * TILE_MARGIN / 2) / 8
	TILE_SIZE_Y = (GAME_AREA_HEIGHT - 6 * TILE_MARGIN / 2) / 8
)
